seed: 1
work_dir: ./exp/ctr/ntu94_xsub/2P/chase
run_mode: train

feeder: feeders.feeder_ntu.Feeder
train_feeder_args:
  data_path: data/ntu120/NTU120_CSub.npz
  split: train
  debug: False
  random_choose: False
  random_shift: False
  random_move: False
  window_size: 64
  normalization: False
  random_rot: True
  p_interval: [0.5, 1]
  vel: False
  bone: False
  random_spatial_shift: True
  action_type: individual
  data_type: 2parts

test_feeder_args:
  data_path: data/ntu120/NTU120_CSub.npz
  split: test  
  debug: False
  window_size: 64
  p_interval: [0.95]
  vel: False
  bone: False
  action_type: individual
  data_type: 2parts

# model
wrapper: model.Wrapper.chas.CHASWrapper
wrapper_args:
  in_channels: 3 
  num_frame: 64
  num_point: 15
  num_entity: 2
  pooling_seg: [1,1,1]
  c1: 64
  c2: 8
model: model.CTRGCN.ctrgcn.Model
model_args:
  num_class: 94
  num_point: 15
  num_person: 2
  graph: model.CTRGCN.graph.ntu_2part.Graph
  graph_args:
    labeling_mode: 'spatial'

#optim
optimizer: SGD
weight_decay: 0.0004
base_lr: 0.1
lr_decay_rate: 0.1
step: [80, 100, 120]
warm_up_epoch: 5
nesterov: True

# loss
loss: CE_MBMMD
loss_args:
  weights: [1.0, 0.1]

# training
device: [0,1,2]
cuda_visible_device: '5,6,7'
batch_size: 72
test_batch_size: 72
num_epoch: 130
eval_interval: 2
