seed: 1
work_dir: ./exp/stsa/ntu26_xsub_joint_chase
run_mode: train

# feeder
feeder: feeders.feeder_ntu.Feeder
train_feeder_args:
  data_path: data/ntu120/NTU120_CSub.npz
  split: train
  debug: False
  random_choose: False
  random_shift: False
  random_move: False
  window_size: 60
  normalization: False
  random_rot: True
  p_interval: [0.5, 1]
  vel: False
  bone: False
  random_spatial_shift: True

test_feeder_args:
  data_path: data/ntu120/NTU120_CSub.npz
  split: test
  debug: False
  window_size: 60
  p_interval: [0.95]
  vel: False
  bone: False
  normalization: False

# model
wrapper: model.Wrapper.chas.CHASWrapper
wrapper_args:
  in_channels: 3 
  num_frame: 60
  num_point: 25
  num_entity: 2
  pooling_seg: [1,1,1]
  c1: 64
  c2: 8
# see https://www.sciencedirect.com/science/article/pii/S0925231222013716 section 4.2
model: model.STSANet.stsanet.Model
model_args:
  len_parts: 3
  num_frames: 60
  num_joints: 25
  num_classes: 26
  num_heads: 3
  kernel_size: [3, 5]
  num_persons: 2
  num_channels: 3
  use_pes: True
  config: [[64,  64,  16], [64,  64,  16], 
           [64,  128, 32], [128, 128, 32],
           [128, 256, 64], [256, 256, 64], 
           [256, 256, 64]]

#optim
optimizer: SGD
weight_decay: 0.0004
base_lr: 0.1
lr_decay_rate: 0.1
step: [60, 90]
warm_up_epoch: 5
nesterov: True

# loss
loss: LSCE_MBMMD
loss_args:
  smoothing: 0.1
  temperature: 1.0
  weights: [1.0, 0.1]

# training
device: [0,1,2,3]
cuda_visible_device: '4,5,6,7'
batch_size: 64
test_batch_size: 64
num_epoch: 110
