seed: 1
work_dir: ./exp/ctr/cad_chase
run_mode: train

# feeder
feeder: feeders.feeder_cad.Collective
train_feeder_args:
  dataset_name: collective
  dataset_dir: data/collective
  joints_folder_name: joints
  tracklets_file_name: tracks_normalized.pkl
  person_action_label_file_name: tracks_normalized_with_person_action_label.pkl
  horizontal_flip_augment: True
  horizontal_flip_augment_purturb: True
  horizontal_move_augment: True
  horizontal_move_augment_purturb: True
  vertical_move_augment: True
  vertical_move_augment_purturb: True
  agent_dropout_augment: True
  image_h: 480
  image_w: 800
  num_classes: 4
  num_person_action_classes: 5
  frame_start_idx: 0
  frame_end_idx: 10
  frame_sampling: 1
  N: 6
  J: 17
  T: 10
  G: 2
  recollect_stats_train: True
  split: train
  print_cls_idx: True
  debug: False

test_feeder_args:
  dataset_name: collective
  dataset_dir: data/collective
  joints_folder_name: joints
  tracklets_file_name: tracks_normalized.pkl
  person_action_label_file_name: tracks_normalized_with_person_action_label.pkl
  image_h: 480
  image_w: 800
  num_classes: 4
  num_person_action_classes: 5
  frame_start_idx: 0
  frame_end_idx: 10
  frame_sampling: 1
  N: 6
  J: 17
  T: 10
  G: 2
  split: test
  print_cls_idx: True
  debug: False

# model
wrapper: model.Wrapper.chas.CHASWrapper
wrapper_args:
  in_channels: 2
  num_frame: 10
  num_point: 17
  num_entity: 6
  pooling_seg: [1,1,1]
  c1: 64
  c2: 8
model: model.CTRGCN.ctrgcn.Model_GROUP
model_args:
  num_class: 4
  num_class_person: 5
  num_point: 17
  num_person: 6
  graph: model.CTRGCN.graph.cad.Graph
  in_channels: 2
  graph_args:
    labeling_mode: 'spatial'

#optim
optimizer: SGD
weight_decay: 0.0004
base_lr: 0.1
lr_decay_rate: 0.1
step: [25, 45]
warm_up_epoch: 5
nesterov: True

# loss
loss: LSCE_MBMMD_GROUP
loss_args:
  smoothing: 0.1
  temperature: 1.0
  weights: [1.0, 1.0]

# training
device: [0,1,2,3,4,5]
cuda_visible_device: '2,3,4,5,6,7'
batch_size: 256
test_batch_size: 256
num_epoch: 55
