seed: 1
work_dir: ./exp/info/ntu11_xsub_k8_chase
run_mode: train

# feeder
feeder: feeders.feeder_ntu.Feeder
train_feeder_args:
  data_path: data/ntu/NTU60_CS.npz
  split: train
  debug: False
  random_choose: False
  random_shift: False
  random_move: False
  window_size: 64
  normalization: False
  random_rot: True
  p_interval: [0.5, 1]
  vel: False
  bone: False
  random_spatial_shift: True

test_feeder_args:
  data_path: data/ntu/NTU60_CS.npz
  split: test  
  debug: False
  window_size: 64
  p_interval: [0.95]
  vel: False
  bone: False
  normalization: False

# model
wrapper: model.Wrapper.chas.CHASWrapper
wrapper_args:
  in_channels: 3 
  num_frame: 64
  num_point: 25
  num_entity: 2
  pooling_seg: [1,1,1]
  c1: 64
  c2: 8
model: model.InfoGCN.infogcn.InfoGCN
model_args:
  graph: model.InfoGCN.graph.ntu_rgb_d.Graph
  num_point: 25
  num_class: 11
  num_head: 3
  num_person: 2
  num_channels: 3
  k: 8
  drop_out: 0
  noise_ratio: 0.5
  config: [[64,  64,  1], [64,  64,  1], [64,  64,  1], 
           [64,  128, 2], [128, 128, 1], [128, 128, 1],
           [128, 256, 2], [256, 256, 1], [256, 256, 1]]

#optim
optimizer: SGD
weight_decay: 0.0005
base_lr: 0.02
lr_decay_rate: 0.1
step: [90, 100]
warm_up_epoch: 5
nesterov: True

# loss
loss: InfoGCN_Loss_MBMMD
loss_args:
  smoothing: 0.1
  temperature: 1.0
  weights: [1.0, 0.1, 0.0001, 0.1]
  class_num: 11
  out_channels: 256
  gain: 3

# training
device: [0,1,2]
cuda_visible_device: '1,2,3'
batch_size: 120
test_batch_size: 120
num_epoch: 110
