seed: 1
work_dir: ./exp/stsa/h2o_chase
run_mode: train

# feeder
feeder: feeders.feeder_h2o.Feeder
train_feeder_args:
  data_path: data/h2o/h2o_pth
  split: train
  debug: False
  random_choose: False
  random_shift: False
  random_move: False
  window_size: 120
  normalization: False
  random_rot: True
  p_interval: [0.5, 1]
  vel: False
  bone: False
  entity_rearrangement: False
  random_spatial_shift: True

test_feeder_args:
  data_path: data/h2o/h2o_pth
  split: val 
  debug: False
  window_size: 120
  p_interval: [0.95]
  vel: False
  bone: False

# model
wrapper: model.Wrapper.chas.CHASWrapper
wrapper_args:
  in_channels: 3 
  num_frame: 120
  num_point: 21
  num_entity: 3
  pooling_seg: [1,1,1]
  c1: 64
  c2: 8
# see https://www.sciencedirect.com/science/article/pii/S0925231222013716 section 4.2
model: model.STSANet.stsanet.Model
model_args:
  len_parts: 6
  num_frames: 120
  num_joints: 21
  num_classes: 36
  num_heads: 3
  kernel_size: [3, 5]
  num_persons: 3
  num_channels: 3
  use_pes: True
  config: [[64,  64,  16], [64,  64,  16], 
           [64,  128, 32], [128, 128, 32],
           [128, 256, 64], [256, 256, 64], 
           [256, 256, 64]]

#optim
optimizer: AdamW
weight_decay: 0.0004
base_lr: 5.e-3
lr_decay_rate: 0.1
step: [60, 90, 120]
warm_up_epoch: 5
nesterov: True

# loss
loss: LSCE_MBMMD
loss_args:
  smoothing: 0.15
  temperature: 1.0
  weights: [1.0, 0.1]

# training
device: [0,1]
cuda_visible_device: '1,2'
batch_size: 16
test_batch_size: 16
num_epoch: 150

