seed: 1
work_dir: ./exp/ctr/ntu11_xview_chase
run_mode: train

# feeder
feeder: feeders.feeder_ntu.Feeder
train_feeder_args:
  data_path: data/ntu/NTU60_CV.npz
  split: train
  debug: False
  random_choose: False
  random_shift: False
  random_move: False
  window_size: 64
  normalization: False
  random_rot: True
  p_interval: [0.5, 1]
  vel: False
  bone: False
  random_spatial_shift: True

test_feeder_args:
  data_path: data/ntu/NTU60_CV.npz
  split: test  
  debug: False
  window_size: 64
  p_interval: [0.95]
  vel: False
  bone: False

# model
wrapper: model.Wrapper.chas.CHASWrapper
wrapper_args:
  in_channels: 3 
  num_frame: 64
  num_point: 25
  num_entity: 2
  pooling_seg: [1,1,1]
  c1: 64
  c2: 8
model: model.CTRGCN.ctrgcn.Model
model_args:
  num_class: 11
  num_point: 25
  num_person: 2
  graph: model.CTRGCN.graph.ntu_rgb_d.Graph
  graph_args:
    labeling_mode: 'spatial'

#optim
optimizer: SGD
weight_decay: 0.0004
base_lr: 0.1
lr_decay_rate: 0.1
step: [80, 100]
warm_up_epoch: 5
nesterov: True

# loss
loss: CE_MBMMD
loss_args:
  weights: [1.0, 0.1]

# training
device: [0,1]
cuda_visible_device: '4,5'
batch_size: 64
test_batch_size: 64
num_epoch: 110
