seed: 1
work_dir: ./exp/info/asb_action_chase
run_mode: asb_test_get_results

# feeder
feeder: feeders.feeder_asb.Feeder_Test
test_feeder_args:
  data_path: data/asb/share_contex25_thresh0/test_data_joint_200.npy
  debug: False
  window_size: 70
  p_interval: [0.95]

# model
wrapper: model.Wrapper.chas.CHASWrapper
wrapper_args:
  in_channels: 3 
  num_frame: 70
  num_point: 21
  num_entity: 2
  pooling_seg: [1,1,1]
  c1: 64
  c2: 8
model: model.InfoGCN.infogcn.InfoGCN
model_args:
  graph: model.InfoGCN.graph.asb.Graph
  num_point: 21
  num_class: 1380
  num_head: 3
  num_person: 2
  num_channels: 3
  k: 1
  drop_out: 0
  noise_ratio: 0.5
  config: [[64,  64,  1], [64,  64,  1], [64,  64,  1], 
           [64,  128, 2], [128, 128, 1], [128, 128, 1],
           [128, 256, 2], [256, 256, 1], [256, 256, 1]]

#optim
optimizer: SGD
weight_decay: 0.0004
base_lr: 0.1
lr_decay_rate: 0.1
step: [35, 45, 55]
warm_up_epoch: 5
nesterov: True

# loss
loss: InfoGCN_Loss_MBMMD
loss_args:
  smoothing: 0.1
  temperature: 1.1
  weights: [1.0, 0.1, 0.0001, 0.01]
  class_num: 1380
  out_channels: 256
  gain: 3

# training
device: [0]
cuda_visible_device: '0'
batch_size: 64
test_batch_size: 64
num_epoch: 60
